
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: day2_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin_user
      RABBITMQ_DEFAULT_PASS: admin_pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/


  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: day2_fastapi
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin_user
      - RABBITMQ_PASS=admin_pass
    depends_on:
      - rabbitmq
    volumes:
      - ./api:/app
    env_file:
      - .env

  worker_email:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: day2_worker_email
    command: python consumer_email.py
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin_user
      - RABBITMQ_PASS=admin_pass
    volumes:
      - ./worker:/app
    env_file:
      - .env


  worker_sms:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: day2_worker_sms
    command: python consumer_sms.py
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin_user
      - RABBITMQ_PASS=admin_pass
    volumes:
      - ./worker:/app
    env_file:
      - .env

volumes:
  rabbitmq_data: