services:
  rabbitmq:
#    image: rabbitmq:3.11-management
    image: docker.arvancloud.ir/rabbitmq:latest
    container_name: ${RABBITMQ_CONTAINER_NAME}
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

  fastapi:
    build:
      context: .
    container_name: ${FASTAPI_CONTAINER_NAME}
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
    env_file:
      - .env

  user_worker:
    build:
      context: .
    container_name: ${USER_WORKER_CONTAINER_NAME}
    command: python worker/consumer_user.py
    depends_on:
      - rabbitmq
    environment:
      - PYTHONPATH=/app:/app/api:${PYTHONPATH}  # Tell Python to find api package
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    volumes:
      - .:/app
    env_file:
      - .env


  order_worker:
    build:
      context: .
    container_name: ${ORDER_WORKER_CONTAINER_NAME}
    command: python worker/consumer_order.py
    depends_on:
      - rabbitmq
    environment:
      - PYTHONPATH=/app:/app/api:${PYTHONPATH}  # Tell Python to find api package
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    volumes:
      - .:/app
    env_file:
      - .env


  error_worker:
    build:
      context: .
    container_name: ${ERROR_WORKER_CONTAINER_NAME}
    command: python worker/consumer_error.py
    depends_on:
      - rabbitmq
    environment:
      - PYTHONPATH=/app:/app/api:${PYTHONPATH}  # Tell Python to find api package
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    volumes:
      - .:/app
    env_file:
      - .env




volumes:
  rabbitmq_data: