
services:
  rabbitmq:
#    image: rabbitmq:4-management
    image: docker.arvancloud.ir/rabbitmq:4-management
    container_name: ${RABBITMQ_CONTAINER_NAME}
    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10


  fastapi:
    build:
      context: .
    container_name: ${FASTAPI_CONTAINER_NAME}
    ports:
      - "8000:8000"

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # Development
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8000           # Production

    depends_on:
      rabbitmq:
        condition: service_healthy

    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - .env



  finance_worker:
    build:
      context: .
    container_name: ${FINANCE_WORKER_CONTAINER_NAME}

    depends_on:
      rabbitmq:
        condition: service_healthy

    command: python -m app.consumers.finance_consumer
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - .env


  high_priority_finance_worker:
    build:
      context: .
    container_name: ${HIGH_PRIORITY_FINANCE_WORKER_CONTAINER_NAME}

    depends_on:
      rabbitmq:
        condition: service_healthy

    command: python -m app.consumers.high_priority_finance_consumer
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - .env



  hr_worker:
    build:
      context: .
    container_name: ${HR_WORKER_CONTAINER_NAME}

    depends_on:
      rabbitmq:
        condition: service_healthy

    command: python -m app.consumers.hr_consumer
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - .env


volumes:
  rabbitmq_data: