services:
  rabbitmq:
#    image: rabbitmq:3.11-management
    image: docker.arvancloud.ir/rabbitmq:latest
    container_name: ${RABBITMQ_CONTAINER_NAME}
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

  fastapi:
    build:
      context: ./api
    container_name: ${FASTAPI_CONTAINER_NAME}
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    depends_on:
      - rabbitmq
    volumes:
      - ./api:/app
    env_file:
      - .env

  info_worker:
    build:
      context: ./worker
    container_name: ${INFO_WORKER_CONTAINER_NAME}
    command: python consumer_info.py
    depends_on:
      - rabbitmq
    environment:
      - PYTHONPATH=/app:/app/api:${PYTHONPATH}  # Tell Python to find api package
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    volumes:
      - ./worker:/app
      - ./api:/app/api   # Mount the api folder inside /app/api
    env_file:
      - .env


  warning_worker:
    build:
      context: ./worker
    container_name: ${WARNING_WORKER_CONTAINER_NAME}
    command: python consumer_warning.py
    depends_on:
      - rabbitmq
    environment:
      - PYTHONPATH=/app:/app/api:${PYTHONPATH}  # Tell Python to find api package
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    volumes:
      - ./worker:/app
      - ./api:/app/api   # Mount the api folder inside /app/api
    env_file:
      - .env


  error_worker:
    build:
      context: ./worker
    container_name: ${ERROR_WORKER_CONTAINER_NAME}
    command: python consumer_error.py
    depends_on:
      - rabbitmq
    environment:
      - PYTHONPATH=/app:/app/api:${PYTHONPATH}  # Tell Python to find api package
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    volumes:
      - ./worker:/app
      - ./api:/app/api   # Mount the api folder inside /app/api
    env_file:
      - .env

  log_router:
    build:
      context: ./worker
    container_name: ${LOG_ROUTER_CONTAINER_NAME}
    command: python log_router.py
    depends_on:
      - rabbitmq
    environment:
      - PYTHONPATH=/app:/app/api:${PYTHONPATH}  # Tell Python to find api package
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    volumes:
      - ./worker:/app
      - ./api:/app/api   # Mount the api folder inside /app/api
    env_file:
      - .env



volumes:
  rabbitmq_data: