
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: ${RABBITMQ_CONTAINER_NAME}
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/


  fastapi:
    build:
      context: ./api
    container_name: ${FASTAPI_CONTAINER_NAME}
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    depends_on:
      - rabbitmq
    volumes:
      - ./api:/app
    env_file:
      - .env

  email_worker:
    build:
      context: ./worker
    container_name: ${EMAIL_WORKER_CONTAINER_NAME}
    command: python consumer_email.py
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    volumes:
      - ./worker:/app
    env_file:
      - .env


  sms_worker:
    build:
      context: ./worker
    container_name: ${SMS_WORKER_CONTAINER_NAME}
    command: python consumer_sms.py
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    volumes:
      - ./worker:/app
    env_file:
      - .env

volumes:
  rabbitmq_data: