
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: day3_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin_user
      RABBITMQ_DEFAULT_PASS: admin_pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/


  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: day3_fastapi
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin_user
      - RABBITMQ_PASS=admin_pass
    depends_on:
      - rabbitmq
    volumes:
      - ./api:/app
    env_file:
      - .env

  worker_info:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: day3_worker_info
    command: python consumer_info.py
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin_user
      - RABBITMQ_PASS=admin_pass
    volumes:
      - ./worker:/app
    env_file:
      - .env


  worker_warning:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: day3_worker_warning
    command: python consumer_warning.py
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin_user
      - RABBITMQ_PASS=admin_pass
    volumes:
      - ./worker:/app
    env_file:
      - .env

        
  worker_error:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: day3_worker_error
    command: python consumer_error.py
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin_user
      - RABBITMQ_PASS=admin_pass
    volumes:
      - ./worker:/app
    env_file:
      - .env

  log_router:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: day3_log_router
    command: python log_router.py
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin_user
      - RABBITMQ_PASS=admin_pass
    volumes:
      - ./worker:/app
    env_file:
      - .env



volumes:
  rabbitmq_data: